### ISSUE TITLE
As a user I want to setup the IDM Wallet locker

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#12]
## Story

As a user I want to setup the locker so that my IDM Wallet is secured.

## Description

Any user must be able to setup their IDM Wallet locker with various methods, one of them being a passphrase. This way, the access to the IDM Wallet is only available to anyone that knows how to unlock it. Moreover, all the local storage will be encrypted and only be accessible with a secret provided by the locker when unlocked.

## Tasks

- [x] #9 
- [x] #10
- [x] #11
 
## Acceptance Criteria

- [x] Have the spec thought out to support multiple locker types, starting with a passphrase
- [x] Have a UI that we can setup the locker using a passphrase
- [x] Have the setup screen implemented in the IDM UI
