### ISSUE TITLE
As a user I want to edit my profile

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-idm#138]
## Story
As a user, I want to edit my profile so that I can edit my info.

## Description
A user should be able to edit his info such as: `name`, `nationality`, `gender`, `photo` and `location`. If the user gives permission, `location` can be automatically inferred by the browser.

## Tasks

- [x] #105 
- [x] #116 
- [x] #118 
 
## Acceptance Criteria

- [x] Include the following details
  - Identity name
  - Avatar
  - Nationality
  - Gender
  - Location
- [x] Implement the identities scope according to the IDM spec
- [x] Implement the "Edit Profile Page".

**Comment by satazor** [comment]
One more user story completed!
