### ISSUE TITLE
As a user I want to be able to unlock the wallet with TouchID or similar

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#147]
## Story

As a user I want to be able to unlock the wallet with TouchID or similar.

## Description

By leveraging WebAuthn we will be able to configure a new LockType that uses hardware within the device.

## Tasks

- [ ] Implement WebAuthn lock type into IDM Wallet
- [ ] Design changes to the lock screen to account for this new lock type
- [ ] Implement the changes to the lock screen in the Nomios app
 
## Acceptance Criteria

- [ ] Be able to configure a new lock type called WebAuthn when available 
- [ ] Be able to unlock IDM with that new lock type
- [ ] Have all of this integrated into Nomios
