### ISSUE TITLE
Implement the Roadmap block

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#159]
## Description

Implement the Roadmap block as designed in #114.

## Acceptance Criteria

- [ ] Implement the roadmap block for desktop
- [ ] Implement the roadmap block for tablet
- [ ] Implement the roadmap block for phone

## To be defined

- [ ] Final items of the roadmap, please reach out @satazor

**Comment by satazor** [comment]
Please reach out to me to list the final items of the roadmap
