### ISSUE TITLE
As a user I want to recognise IDM by its unique brand

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#17]
## Story

As a user I want to recognise IDM by its unique brand so that I easily remember it. 

## Description

The IDM brand should have the following keypoints embed in it: `identity`, `classy`, `formal`, `trustworthy`, `reliable`. Both the symbol, brand and interfaces should have these keypoints in consideration.

Also, the `IDM` is a codename and we must decide on the final name.
 
## Tasks

- [x] #19
- [x] #18
- [x] #6 
 
## Acceptance Criteria

- [x] Have the IDM brand concept according to the keypoints listed above
- [x] Have the final name for the project
- [x] All the repository information and names should reflect the final name
- [x] Include the output in the repository
- [ ] Update this repo's README to include the logo

**Comment by satazor** [comment]
Wallet spec name: Identity Manager
First wallet that implements the spec: Nomios
