### ISSUE TITLE
As a user I want to backup my identity

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#181]
## Story

As a user I want to backup my identity, storing the backup data containing the mnemonic and other things.

## Tasks

- [x] #26
- [x] #173  

## Acceptance Criteria

- [x] User must be able to manually write the 12 words, the PDF and QR codes will come later
- [x] We must ensure the user really wrote those words with a verification step
- [x] Erase the backup data from the wallet when the process is completed
