### ISSUE TITLE
As a user I want to backup/import my identity with a PDF file

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-idm#225]
## Story
As a user, I want to backup my identity by saving a PDF file

## Description
The user must be able to save a PDF file with his identity's mnemonic and other potential recovery methods (e.g. QR code).

## Tasks

- [x] #27 (placeholder implementation)
- [x] #173 (placeholder implementation)
- [ ] #224
- [ ] #275 
 
## Acceptance Criteria

- [x] Backup-identity has the PDF skeleton implemented
- [x] Import-identity has the PDF skeleton implemented
- [ ] Backup-identity has the PDF skeleton fully integrated and working properly
- [ ] Import-identity has the PDF skeleton fully integrated and working properly

**Comment by PedroMiguelSS** [comment]
Closing this in favor of #250 and #251.
