### ISSUE TITLE
As a user I want to be able to create a new DID

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#24]
## Story

As a user I want to be able to create a new DID so that I own my own identity.

## Description

A user should be able to create an identity from scratch, using the IPID DID method. A master key and device keys are created during the process and will be listed in the DID document. In the end, the user is asked to optionally backup master key via paper key.
 
Moreover, personal details such as the name and avatar will be prompted but won't be used until we implement the user-story that for editing the identity details.

## Tasks

- [x] #26
- [x] #29
- [x] #28
- [x] #30
- [x] #82 
- [x] #83 

## Acceptance Criteria

- [ ] Be able to create a new DID based on the IPID DID method, where both the master and device keys are listed in the DID document and the device key is referenced in the `authentication` field
- [x] Ask the `name` and `avatar` during the creation process
- [x] Prompt the user to backup the master key via a paper key

**Comment by satazor** [comment]
@paulobmarcos I think we are missing adding the device key in the authentication field of the DIDDoc, is this correct?

**Comment by satazor** [comment]
This was done in the sessions & signing effort on the reference IDM Wallet implementation!
