### ISSUE TITLE
As a user I want to be able to see all my devices, social proofs and apps

### ISSUE THREAD

**Issue by paulobmarcos** [ipfs-shipyard/pm-idm#261]
## Story

As a user I want to be able to see all my devices, social proofs and apps

## Description

Currently we are only able to see a few devices, social proofs and apps on an identity profile page. There should a "page" to see all devices, social proofs and apps and have a better way to manage them.

## Tasks

- [ ] Task #
- [ ] Task #
- [ ] Task #
 
## Acceptance Criteria

- [ ] As a user I want to be able to see all my apps.
- [ ] As a user I want to be able to see all my devices.
- [ ] As a user I want to be able to see all my social proofs.
