### ISSUE TITLE
As a user I want to see the identities overview on the homepage

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-idm#279]
## Description

The homepage of the app should work as an overview of the multiple identities with possible entry-points for each one of them, the idea should be see at a glance we various states of each identity or highlight something in specific from them.

## Tasks

- [ ] Brainstorm "What should the users can see on the homepage?"
- [ ] #115 
 
## Acceptance Criteria

- [ ] Define IA, content and features for the homepage
- [ ] Design the homepage with multiple states/highlights of each identity
