### ISSUE TITLE
As a user I want to be able to run a wallet as a desktop app

### ISSUE THREAD

**Issue by paulobmarcos** [ipfs-shipyard/pm-idm#281]
## Story

As a user I want to be able to run a wallet as a desktop app.

## Description

Users still use their desktops/laptops for multiple purposes due to the versatility/capability to do certain tasks. For convenience there should be a desktop version of Nomios so that the user can have it running in the background while using their device.

## Tasks

- [ ] 
 
## Acceptance Criteria

- [ ] Research how the current UI/UX elements of the web version would be fit on a desktop version of Nomios.
- [ ] Design new elements UI/UX elements  for the desktop version of Nomios.
- [ ] Create IDM support for desktop apps.
- [ ] Build Nomios as a cross platform desktop app using Electron.
