### ISSUE TITLE
As a user I want to see my Identity page

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#46]
## Story

As a user I want to see my Identity page so that I get an overview of it.

## Description

Have a Identity page displaying a summary of the Identity with the ability to start other journeys, such as: editing the identity, managing credentials, managing apps and managing devices

## Tasks

- [x] #171 
- [x] #117
- [x] #92 
 
## Acceptance Criteria

- [x] Must contain a summary with the identity details and social proofs
- [x] Must contain the ability to change the identity details and manage social proofs (mocked)
- [x] Could display the latest used apps & devices
- [x] Must contain links to view all apps & devices
