### ISSUE TITLE
As a user I want to see my list of Identities within the IDM Wallet UI shell

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#47]
## Story

As a user I want to see my list of Identities within the IDM UI shell so that I can quickly get into their pages.

## Description

The IDM Wallet UI shell/chrome should contain a list of identities associated with the wallet, possibly on the left

## Tasks
 
- [x] #61 
- [x] #120 
- [x] #104 

## Acceptance Criteria

- [x] List all the identities associated with the Wallet
- [x] Clicking on it should led the user to the Identity page
- [x] Should account for the resolution, that is, it should handle a list that doesn't fit the screen

**Comment by satazor** [comment]
All done!
